spring.application.name=E-Commerce-App
spring.datasource.url=${database_url}
spring.datasource.username=${database_user_name}
spring.datasource.password=${DatabasePassword}

admin.contact_number=${admin_contact_number}
admin.password=${admin_password}
admin.email=${admin_email}

spring.devtools.restart.enabled=true